### PR TITLE
MQTTConnect add userName,password

### PR DESCRIPTION
**Pull request by zhaoyouzhi**

### CODE REVIEW

**Comment by agoransson** [comment]
Thanks! I'll have a look at this tonight. The diff seems very big for such a small change, so I'm a bit hesitant to accept it right off the bat.

**Comment by agoransson** [comment]
@zhaoyouzhi Can you have a look at the diff for `QatjaService.java`? It seems as though the file has been reorganized, or the lineendings has changed or something. I can't quite make out what you've changed.

**Comment by zhaoyouzhi** [comment]
I added the method of setting the username and password, and in the connect method to determine whether it is null, call connect(clientIdentifier, userName, password);

**Comment by agoransson** [comment]
Since this PR included so many unnecessary changes I'm closing it, but the fix is now built into version 0.1.21. Thank you for pointing the missing feature out! Sorry for the delay.

**Pull request closed without merging**
