### PR TITLE
Remember and retrieve subscribed topics

### PR DESCRIPTION
**Pull request by faeibson**
The subscribed topics are stored and can be retrieved.

### CODE REVIEW

**Comment by faeibson** [comment]
...and it is now prevented to subscribe topics multiple times.

**Comment by agoransson** [comment]
Hey, thanks for the work! I'll fix the build-scripts and then accept.

**Comment by agoransson** [comment]
This will be published in 0.1.12, just can't sit more right now researching the problem with bintray uploads.

**Comment by faeibson** [comment]
I've just noticed that obviously it would be much better to put the aggregation of `subscribedTopics ` in `handleSubscriptions()` than in `subscribe()`, don't you think? So the subscriptions actually need to be confirmed - as well as unsubscriptions. Unfortunately I have overlooked that function. If you like, I would change, test and commit that approach.

**Comment by agoransson** [comment]
You're of course right, but as of now it doesn't matter much. My plan for the fall/winter is to rewrite this library into kotlin - and in that work refactor quite a lot.

I'm satisfied that this fix will work for users and that's the goal for now.

**Comment by agoransson** [comment]
So, had some time tonight to sit down and read build logs... seems bintray refuses to accept uploads with a little bit older plugin versions now. So, I've upgraded the plugin and the changes should now, finally..., be available in 0.1.12

**Comment by faeibson** [comment]
I see! Great, but sorry for the mess I've caused!

**Pull request merged**
